openapi: 3.0.1
info:
  title: orderProducerApi
  description: API Definition of orderProducerApi
  version: 1.0.0
servers:
- url: http://localhost:8290/produce
paths:
  /:
    post:
      responses:
        default:
          description: Default response
